xpCost: 1 # The amount of experience points required to repair 1 durability point
repairAmount: 2 # The amount of durability points repaired per use

# List of enchantments that are allowed to be used with the repair feature.
# The plugin will only use enchantments from this list for repair.
# Enchantments should be specified using their Minecraft ID (e.g. MENDING, PROTECTION).
# To allow all enchantments, specify "any" (without quotes).
allowedEnchantments:
 - MENDING
